name: foreclose

on:
  schedule:
    - cron: '0 4 * * 2' # in the midnight Monday to Tuesday UTC-4 (Tuesday at 04.00 AM UTC)
    - cron: '0 4 * * 4' # Thursday
    - cron: '0 4 * * 6' # Saturday
  
  workflow_dispatch:

jobs:
  scraping-time:
    runs-on: ubuntu-latest  
    
    services:
      selenium:
        image: selenium/standalone-chrome:latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1'
      
      - name: Install dependency
        run: sudo apt install libcurl4-openssl-dev
      
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
      
      - name: Run scraper
        env:
          CRED_PATH: ${{ secrets.CRED_PATH }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          SHEETS_FORECLOSE: ${{ secrets.SHEETS_FORECLOSE }}
        run: | 
          echo $SECRET_TOKEN >> $CRED_PATH
          Rscript foreclose.R
          rm $CRED_PATH
          
      - name: Set today
        id: set_today
        run: | 
          echo "::set-output name=today::$(date +'%a, %F at %H:%M %Z')"
        
      - name: Commit result
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated: ${{ steps.set_today.outputs.today }}"
          file_pattern: history/*.csv *.rds
          
