name: python-scraper

on:
  push:
    branches:
      - 'python'

jobs:
  scraping-time:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install modules
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps firefox
        
      - name: Run python scraper
        run: | 
          python main.py
          
      - name: Commit result
        shell: bash {0}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add history/*.json
          timestamp=$(TZ='America/New_York' date +'%a, %F at %H:%M %Z')
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
