name: python-scraper

on:
  push:
    branches:
      - 'python'

jobs:
  scraping-time:
    runs-on: ubuntu-latest  
    
    services:
      playwright:
        image: mcr.microsoft.com/playwright/python
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run python scraper
        run: | 
          python main.py
          
      - name: Commit result
        shell: bash {0}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add history/*.json
          timestamp=$(TZ='America/New_York' date +'%a, %F at %H:%M %Z')
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
