name: scraper-3rd-bidder

on:
  push:
    branches:
      - 'scrapdev2'
  schedule:
    - cron: '0 23 * * 1-5' # 11:00 PM UTC (6:00 PM EST) every weekday (Monday to Friday)

jobs:
  scraping:
    if: github.ref == 'refs/heads/scrapdev2' # Only run on 'scrapdev2' branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: scrapdev2 # Checkout scrapdev2 branch
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install python module
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps firefox
      
      - name: Run scraper
        run: python scraper_bid.py
          
      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add history/*.json
          timestamp=$(TZ='America/New_York' date +'%a, %F at %H:%M %Z')
          git commit -m "Scraping updated: ${timestamp}" || exit 0
          git push

  forwarding:
    runs-on: ubuntu-latest
    needs: scraping
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: scrapdev2 # Checkout scrapdev2 branch
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1'
        
      - name: Install R library
        run: |
          sudo apt-get install libcurl4-openssl-dev
          Rscript -e 'install.packages(c("dplyr", "googlesheets4", "jsonlite"))'
        
      - name: Run wrangler
        run: Rscript wrangle_bid.R
        
      - name: Run forwarder
        env:
          CRED_PATH: ${{ secrets.CRED_PATH }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          SHEETS_FORECLOSE: ${{ secrets.SHEETS_FORECLOSE }}
          SHEETS_TAXDEED: ${{ secrets.SHEETS_TAXDEED }}
          SHEETS_TEST: ${{ secrets.SHEETS_TEST }}
        run: | 
          echo $SECRET_TOKEN >> $CRED_PATH
          Rscript foreclose_bid.R
          Rscript taxdeed_bid.R
          rm $CRED_PATH
        
      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add *.rds history/foreclose/*.csv history/taxdeed/*.csv
          timestamp=$(TZ='America/New_York' date +'%a, %F at %H:%M %Z')
          git commit -m "Data updated: ${timestamp}" || exit 0
          git push