name: scraper

on:
  schedule:
    - cron: '0 4 * * 6' # in the midnight Friday to Saturday UTC-4 (Saturday at 04.00 AM UTC)
  
  workflow_dispatch:

jobs:
  scraping-time:
    runs-on: ubuntu-latest  
    
    services:
      selenium:
        image: selenium/standalone-chrome:latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1'
      
      - name: Install dependency
        run: sudo apt install libcurl4-openssl-dev
      
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
      
      - name: Run scraper
        env:
          CRED_PATH: ${{ secrets.CRED_PATH }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          SHEETS_ID: ${{ secrets.SHEETS_ID }}
        run: | 
          echo $SECRET_TOKEN >> $CRED_PATH
          Rscript auction.R
          Rscript sheets.R
          rm $CRED_PATH
          
      - name: Commit result
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated: `date +'%a, at %F %H:%M %Z'`"
          file_pattern: "*.rds"
