name: taxdeed

on:
  workflow_run:
    workflows: ["foreclose"]
    types:
      - completed
  
  workflow_dispatch:

jobs:
  scraping-time:
    runs-on: ubuntu-latest  
    
    services:
      selenium:
        image: selenium/standalone-chrome:latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1'
      
      - name: Install dependency
        run: sudo apt install libcurl4-openssl-dev
      
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
      
      - name: Run scraper
        env:
          CRED_PATH: ${{ secrets.CRED_PATH }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          SHEETS_TAXDEED: ${{ secrets.SHEETS_TAXDEED }}
          SHEETS_TEST: ${{ secrets.SHEETS_TEST }}
        run: | 
          echo $SECRET_TOKEN >> $CRED_PATH
          Rscript taxdeed.R
          rm $CRED_PATH
          
      - name: Commit result
        shell: bash {0}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add history/taxdeed/*.csv *.rds
          timestamp=$(TZ='America/New_York' date +'%a, %F at %H:%M %Z')
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
